version: "2"
volumes:
  node_modules:
  build:
services:
  web:
    build: .
    command: mix phx.server
    volumes:
      - .:/app
      - node_modules:/app/assets/node_modules
      - build:/app/_build
    ports:
      - "4000:4000"